# Generated by Django 4.0.4 on 2022-08-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_alter_profile_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='user',
        ),
    ]
