# Generated by Django 4.0.4 on 2022-08-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_profile_img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
