# Generated by Django 4.0.4 on 2022-08-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_followercount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowerCount',
            new_name='FollowersCount',
        ),
    ]
